


-- for cleaning up .aux .log file etc
-- >> latexmk -c 

-- removing all file generated by the compilation of .tex (including pdf)
-- >> latexmk -C


-- changing the default PDF preview application
-- Skim is used
vim.g['vimtex_view_method'] = 'skim'
